### ISSUE TITLE
Constellation (DVP)

### ISSUE THREAD

**Issue by asadmehdi785** [arielnicolelee/constellation#1]
### Criteria 1: Matplotlib and CSV
* _Score Level:_ 4
* _Comment(s):_ The Jupyter notebook file imports the libraries necessary for the project.
 
### Criteria 2: Implementation of 2D Visualization
* _Score Level:_ 4
* _Comment(s):_ The 2D grid appears with data plotted on the graph and the visualization includes custom color or a title.
 
### Criteria 3: Implementation of 3D Visualization
* _Score Level:_ 4
* _Comment(s):_ The 3D grid appears with the correct data plotted on the graph. The grid is rotatable. There is a title on the graph.
 
### Overall Score: 12/12
Excellent work on this project! You did a good job utilizing matplotlib to implement the visualizations for the project. I especially liked how you included labels for the axis and titles for both graphs. Great work!

If you want to add a label for the z-axis on the 3D visualization, you can try using `ax.set_zlabel`.

Good job overall! I hope you enjoy the rest of course!

**Comment by arielnicolelee** [comment]
Thanks so much! And thanks for the tip about labeling the z-axis - I was trying to figure that out!
